---
- name: Download and clean miner logs
  hosts: miners
  become: yes
  vars:
    local_log_dir: "{{ lookup('ansible.builtin.env', 'SUBNET_DIR') }}/38/logs"
    remote_out_log_path: "/root/.pm2/logs/distributed-training-miner-out.log"
    remote_err_log_path: "/root/.pm2/logs/distributed-training-miner-error.log"
    fetch_error_logs: false

  tasks:
    - name: Ensure local log directory exists
      local_action:
        module: file
        path: "{{ local_log_dir }}"
        state: directory
        mode: '0755'
      become: false

    - name: Set timestamp
      set_fact:
        log_timestamp: "{{ lookup('pipe', 'date +%y-%m-%d-%H-%M') | trim }}"

    - name: Set local out log filename
      set_fact:
        out_log_file: "{{ local_log_dir }}/{{ ('' if network != 'test' else 'T') }}{{ log_timestamp }}_{{ 't' if network == 'test' else 'm' }}{{ miner_uid }}.log"

    - name: Set local error log filename
      set_fact:
        err_log_file: "{{ local_log_dir }}/{{ ('' if network != 'test' else 'T') }}{{ log_timestamp }}_{{ 't' if network == 'test' else 'm' }}{{ miner_uid }}_err.log"

    - name: Fetch PM2 out log from remote miner
      fetch:
        src: "{{ remote_out_log_path }}"
        dest: "{{ out_log_file }}"
        flat: yes

    - name: Fetch PM2 error log from remote miner
      fetch:
        src: "{{ remote_err_log_path }}"
        dest: "{{ err_log_file }}"
        flat: yes
      when: fetch_error_logs

    - name: Clean PM2 out log locally (remove color codes)
      command: sed -i -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' "{{ out_log_file }}"
      delegate_to: localhost
      become: false

    - name: Clean PM2 error log locally (remove color codes)
      command: sed -i -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' "{{ err_log_file }}"
      delegate_to: localhost
      become: false
      when: fetch_error_logs

    - name: Remove empty lines from PM2 out log
      command: sed -i '/^$/d' "{{ out_log_file }}"
      delegate_to: localhost
      become: false

    - name: Remove empty lines from PM2 error log
      command: sed -i '/^$/d' "{{ err_log_file }}"
      delegate_to: localhost
      become: false
      when: fetch_error_logs

    - name: Notify user
      debug:
        msg: >
          Logs saved to {{ out_log_file }}
          {% if fetch_error_logs %} and {{ err_log_file }}{% endif %}

    - name: Open PM2 out log in VS Code
      command: code "{{ out_log_file }}"
      delegate_to: localhost
      become: false

    - name: Open PM2 error log in VS Code
      command: code "{{ err_log_file }}"
      delegate_to: localhost
      become: false
      when: fetch_error_logs

