experiment: detection   # detection | classification

detection:
  model_type: yolo # yolo | sam
  # data_path: /media/jorrit/ssd/phd/moths/configs/nid_det.yaml # YAML
  data_path: ~/moths/configs/nid_det.yaml # YAML

  yolo:
    number: 8
    model_size: n # n=nano, s=small, m=medium, l=large, x=xlarge

  sam:
    model_type: vit_h  # vit_h  # vit_h, vit_l, vit_b # is this a mistake????

  params:
    epochs: 1
    imgsz: 640
    device: cpu
    # recommended:
    # cpu: epochs: 1, imgsz: 640, device: cpu
    # gpu: epochs: 20, imgsz: 640, device: 0

classification:
  model_type: yolo   # yolo | vit
  data_path: /path/to/eu_cls_folder # FOLDER

  params:
    epochs: 20
    imgsz: 224
    device: cpu
    batch: 32
    workers: 8
    optimizer: Adam
    learning_rate: 2e-5
    weight_decay: 0.01
    warmup_steps: 500    
  
  yolo:
    number: 8
    model_size: nano # nano, small, medium, large, xlarge

  vit:
    model_size: base  # base, large, huge  
    num_labels: 100  # number of classes
