[vast_gpus]
    33452618 ansible_host=ssh8.vast.ai ansible_port=12618 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes'

    [vast_gpus:vars]
    instance_id=33452618
    gpu_name=RTX 3090
    gpu_count=1
    location=Spain, ES
    ssh_command=ssh -p 12618 root@ssh8.vast.ai
    